name = "mtgink-images"
main = "src/index.ts"
compatibility_date = "2025-12-01"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["0 * * * *"]
account_id = "7dad892db6ba7c0845a9a8572da362fc"

[observability]
enabled = true

[[containers]]
class_name = "ImageScraper"
image = "registry.cloudflare.com/7dad892db6ba7c0845a9a8572da362fc/mtgink-images-imagescraper:v3"
max_instances = 1
instance_type = "standard-1"

[[durable_objects.bindings]]
name = "IMAGE_SCRAPER"
class_name = "ImageScraper"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ImageScraper"]
